# SINGLE TABLE VIEW

CREATE VIEW MENUNAME_AND_PRICE  AS
SELECT MENU_ID,MENU_NAME,MENU_PRICE
FROM MENU;

SELECT * FROM MENUNAME_AND_PRICE;
 
# MULTIPLE TABLE VIEW 
 
CREATE VIEW WHAT_MENU_IS_ORDERED_CUSTOMER AS
SELECT ORDERS.CUSTOMER_ID,
       ORDERS.ORDER_ID,
	   MENU.MENU_ID,
	   MENU.MENU_NAME
FROM MENU,ORDERS WHERE ORDERS.ORDER_ID=MENU.ORDER_ID;
       
SELECT * FROM WHAT_MENU_IS_ORDERED_CUSTOMER;
DROP VIEW WHAT_MENU_IS_ORDERED_CUSTOMER;

#stored procedure WITHOUT PASSING VALUES
DELIMITER //
CREATE PROCEDURE MENU_PRICES()
BEGIN
SELECT * FROM MENU;
END;

CALL MENU_PRICES;

# WITH PASSING VALUES(IN,OUT)
# IN PROCEDURE

DELIMITER //
CREATE PROCEDURE CUSTOMER_ADDRES(IN CUSTO_ID INT,CUSTO_NAME VARCHAR(50))
BEGIN 
SELECT CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDRESS FROM CUSTOMER WHERE CUSTOMER_ID > CUSTO_ID or CUSTOMER_NAME!=CUSTO_NAME; 
END;
CALL CUSTOMER_ADDRES(105,'T JANARDHAN');

# OUT PROCEDURE

DELIMITER //
CREATE PROCEDURE TOTAL_CUSTOMERS(OUT TOTAL_CUSTO INT)
BEGIN
SELECT COUNT(CUSTOMER_ID) INTO TOTAL_CUSTO FROM CUSTOMER;
END;
CALL TOTAL_CUSTOMERS(@TOTAL_CUSTO);
SELECT @TOTAL_CUSTO;



DELIMITER //
CREATE PROCEDURE MENU_PRICE_INCREASE(INOUT MENU_IID INT,INOUT MENU_PRICES DOUBLE)
BEGIN
select MENU_PRICE INTO MENU_PRICES FROM MENU WHERE MENU_ID=MENU_IID;
set MENU_PRICES=MENU_PRICES*1;
UPDATE MENU SET MENU_PRICE=MENU_PRICES where MENU_ID=MENU_ID;
END;
set @MENU_IID=302;
call MENU_PRICE_INCREASE(@MENU_ID,@MENU_PRICE);

